// Datos de iglesias por sector
export const CHURCHES_DATA = [
  { sector: 1, name: "Monte Olivar" },
  { sector: 1, name: "Silo Comunidad Cristiana" },
  { sector: 1, name: "Centro Familiar Monte Sinai" },
  { sector: 1, name: "Misión Apostólica Betsaida" },
  { sector: 1, name: "Casa de Oración" },
  { sector: 1, name: "Iglesia San Ángel" },
  { sector: 1, name: "Iglesia Fuente Inagotable" },
  { sector: 1, name: "Iglesia Luz y Salvación" },
  { sector: 1, name: "Remanente de Vida" },
  { sector: 1, name: "Antioquia la Hermosa" },
  { sector: 1, name: "Iglesia Misión Libertad" },
  { sector: 1, name: "Tabernáculo de Adoración Familiar" },
  { sector: 1, name: "Cristo Centro de la Familia" },
  { sector: 1, name: "Iglesia Principe de Paz" },
  { sector: 2, name: "La Nueva Jerusalén" },
  { sector: 2, name: "Comunidad Cristiana" },
  { sector: 2, name: "Iglesia Nueva Esperanza Tijuana" },
  { sector: 2, name: "León de Judá" },
  { sector: 2, name: "Monte Sion Tijuana" },
  { sector: 2, name: "Iglesia Jesucristo es la Roca" },
  { sector: 2, name: "Iglesia el Manantial" },
  { sector: 2, name: "Asamblea Apostólica" },
  { sector: 2, name: "Centro Familiar Nuevo Amanecer" },
  { sector: 2, name: "El Refugio" },
  { sector: 2, name: "Iglesia Bethesda" },
  { sector: 2, name: "Tabernáculo de Fe Tijuana" },
  { sector: 2, name: "Maranatha" },
  { sector: 3, name: "1a Asamblea Apostólica Centro Cristiano Avivamiento" },
  { sector: 3, name: "9na Asamblea Apostólica" },
  { sector: 3, name: "8va Asamblea Apostólica" },
  { sector: 3, name: "6ta Asamblea Apostólica Torre Fuerte" },
  { sector: 3, name: "Eben-Ezer Ejido Nuevo León" },
  { sector: 3, name: "7ma Asamblea Apostólica Betesda" },
  { sector: 3, name: "3ra Asamblea Apostólica La Gran Comisión" },
  { sector: 3, name: "10ma Asamblea Apostólica Sendas Antiguas" },
  { sector: 3, name: "5ta Asamblea Apostólica Avivamiento y Poder" },
  { sector: 3, name: "Asamblea Apostólica Casa de Dios y Puerta del Cielo" },
  { sector: 3, name: "11ra Asamblea Apostólica Palabra Viva" },
  { sector: 3, name: "12va Asamblea Apostólica Casa de Bendición" },
  { sector: 3, name: "13va Asamblea Apostólica Siloé" },
  { sector: 4, name: "Capernaum" },
  { sector: 4, name: "Jesucristo Camino a la Sal" },
  { sector: 4, name: "Iglesia Vida Nueva" },
  { sector: 4, name: "Fuente de Salvación" },
  { sector: 4, name: "Paz de Cristo" },
  { sector: 4, name: "Betesda Casa de Misericordia" },
  { sector: 4, name: "Nueva Vida Camalú" },
  { sector: 4, name: "Asamblea Apostólica" },
  { sector: 4, name: "El Buen Camino" },
  { sector: 4, name: "Iglesia Shalom" },
  { sector: 5, name: "Iglesia Casa de Gracia" },
  { sector: 5, name: "Eben-Ezer Ojos Negros" },
  { sector: 5, name: "Iglesia Familias con Propósito" },
  { sector: 5, name: "Asamblea Apostólica" },
  { sector: 5, name: "Templo Jerusalén" },
  { sector: 5, name: "Iglesia Visión" },
  { sector: 5, name: "Misión Bethel" },
  { sector: 5, name: "Iglesia La Vid Verdadera" },
  { sector: 5, name: "Castillo de Fe" },
  { sector: "Foráneo", name: "Sin Iglesia Sectoral" }
];